### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by manorit2001** [parth-07/cgpa_book_server#12]
We can add this https://github.com/marketplace/actions/git-deploy-to-heroku for development and master branch. This will help in testing as well as it will allow the master branch to remain in sync with heroku

**Comment by manorit2001** [comment]
https://probot.github.io/apps/deploy/

**Comment by manorit2001** [comment]
deploy

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@github deploy
